### ISSUE TITLE
Unable to fetch module - "error":"invalid_parameter","error_message":"Invalid platform specified."

### ISSUE THREAD

**Issue by BhagiLimbu** [elasticio/sugarcrm-component#32]
After click on drop down list (Select a SugarCRM module), it show an error message. Here's a log information: 

`
Starting your Docker container ...

[INFO  tini (1)] Spawned child process '/run.sh' with pid '7'

Starting application in apprunner...

Starting slug download ...

Successfully downloaded and extracted slug file

node: /usr/lib/libstdc++.so.6: no version information available (required by node)

node: /usr/lib/libstdc++.so.6: no version information available (required by node)

node: /usr/lib/libstdc++.so.6: no version information available (required by node)

node: /usr/lib/libstdc++.so.6: no version information available (required by node)

node: /usr/lib/libstdc++.so.6: no version information available (required by node)

node: /usr/lib/libstdc++.so.6: no version information available (required by node)

No access token found.  Fetching access token with user credentials...

{"error":"invalid_parameter","error_message":"Invalid platform specified."}

at fetchAndSaveToken (/home/apprunner/lib/sugarcrm.js:94:14)

at process._tickCallback (internal/process/next_tick.js:169:7) 'Error: Unexpected response from provider.  Status code: 422 Body: \n            {"error":"invalid_parameter","error_message":"Invalid platform specified."}\n    at wasAuthenticationSuccessful (/home/apprunner/lib/sugarcrm.js:79:15)\n    at fetchAndSaveToken (/home/apprunner/lib/sugarcrm.js:94:14)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:169:7)'

Error: Unexpected response from provider.  Status code: 422 Body:

at <anonymous>

at wasAuthenticationSuccessful (/home/apprunner/lib/sugarcrm.js:79:15)

[INFO  tini (1)] Main child exited normally (with status '0')

`

any suggestions?

**Comment by jhorbulyk** [comment]
@BhagiLimbu As part of your credentials, are you providing a platform value that matches the one you created in https://github.com/elasticio/sugarcrm-component#registering-a-new-sugarcrm-platform-value-through-the-ui ?
